version: "3.3"
services:
  database:
    image: "postgres:13"
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql